server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petales
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: petales
    password: petales

mybatis:
  mapper-locations: mybatis/mapper/*.xml

thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"