server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://222.112.124.237:3306/pettales
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pettales
    password: pettales

mybatis:
<<<<<<< HEAD
  mapper-locations: mapper/*.xml
=======
  mapper-locations: mybatis/mapper/*.xml

thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"
>>>>>>> c900a189ded6e68bdd37d20062cd471e37cd56a5
